# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polish_verbs_2.ui'
#
# Created: Mon Mar 20 14:06:14 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 445)
        MainWindow.setMaximumSize(QtCore.QSize(596, 445))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 50, 161, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verb = QtGui.QLabel(self.centralwidget)
        self.verb.setGeometry(QtCore.QRect(10, 20, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Buxton Sketch")
        font.setPointSize(28)
        self.verb.setFont(font)
        self.verb.setAlignment(QtCore.Qt.AlignCenter)
        self.verb.setObjectName("verb")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 200, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.ja = QtGui.QLineEdit(self.centralwidget)
        self.ja.setGeometry(QtCore.QRect(142, 109, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ja.setFont(font)
        self.ja.setText("")
        self.ja.setObjectName("ja")
        self.ty = QtGui.QLineEdit(self.centralwidget)
        self.ty.setGeometry(QtCore.QRect(140, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ty.setFont(font)
        self.ty.setText("")
        self.ty.setObjectName("ty")
        self.on_ona_ono = QtGui.QLineEdit(self.centralwidget)
        self.on_ona_ono.setGeometry(QtCore.QRect(140, 210, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.on_ona_ono.setFont(font)
        self.on_ona_ono.setText("")
        self.on_ona_ono.setObjectName("on_ona_ono")
        self.oni_one = QtGui.QLineEdit(self.centralwidget)
        self.oni_one.setGeometry(QtCore.QRect(420, 210, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.oni_one.setFont(font)
        self.oni_one.setText("")
        self.oni_one.setObjectName("oni_one")
        self.my = QtGui.QLineEdit(self.centralwidget)
        self.my.setGeometry(QtCore.QRect(422, 109, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.my.setFont(font)
        self.my.setText("")
        self.my.setObjectName("my")
        self.wy = QtGui.QLineEdit(self.centralwidget)
        self.wy.setGeometry(QtCore.QRect(420, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.wy.setFont(font)
        self.wy.setText("")
        self.wy.setObjectName("wy")
        self.check_button = QtGui.QPushButton(self.centralwidget)
        self.check_button.setGeometry(QtCore.QRect(320, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.check_button.setFont(font)
        self.check_button.setObjectName("check_button")
        self.new_verb_button = QtGui.QPushButton(self.centralwidget)
        self.new_verb_button.setGeometry(QtCore.QRect(170, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_verb_button.setFont(font)
        self.new_verb_button.setObjectName("new_verb_button")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 350, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_with_result = QtGui.QLabel(self.centralwidget)
        self.label_with_result.setGeometry(QtCore.QRect(250, 350, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_with_result.setFont(font)
        self.label_with_result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_with_result.setObjectName("label_with_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ja, self.ty)
        MainWindow.setTabOrder(self.ty, self.on_ona_ono)
        MainWindow.setTabOrder(self.on_ona_ono, self.my)
        MainWindow.setTabOrder(self.my, self.wy)
        MainWindow.setTabOrder(self.wy, self.oni_one)
        MainWindow.setTabOrder(self.oni_one, self.new_verb_button)
        MainWindow.setTabOrder(self.new_verb_button, self.check_button)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Polish Verbs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Print correct forms of the verb", None, QtGui.QApplication.UnicodeUTF8))
        self.verb.setText(QtGui.QApplication.translate("MainWindow", "VERB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "ja", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "on/ona/ono", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "ty", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "my", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "wy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "oni/one", None, QtGui.QApplication.UnicodeUTF8))
        self.check_button.setText(QtGui.QApplication.translate("MainWindow", "Check forms!", None, QtGui.QApplication.UnicodeUTF8))
        self.new_verb_button.setText(QtGui.QApplication.translate("MainWindow", "New verb", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Number of right answers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_with_result.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))

